apiVersion: v1
data:
  config.yaml: "enableNodeSelector: false\nenabled: true\nmountPodPatch: \n  - resources:\n
    \     requests:\n        cpu: 8\n        memory: 8Gi\n      limits:\n        memory:
    16Gi"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: juicefs-csi-driver
    meta.helm.sh/release-namespace: juicefs-csi
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: juicefs-csi-driver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: juicefs-csi-driver
    app.kubernetes.io/version: 0.29.2
    helm.sh/chart: juicefs-csi-driver-0.29.2
  name: juicefs-csi-driver-config
  namespace: juicefs-csi
